create table livre (id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (dtype varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), etat varchar(255), id_exp bigint, primary key (id_livre)) engine=InnoDB;
create table livre (dtype varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), etat varchar(255), id_exp bigint, primary key (id_livre)) engine=InnoDB;
create table livre (dtype varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), etat varchar(255), id_exp bigint, primary key (id_livre)) engine=InnoDB;
create table livre (type_personne varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), etat varchar(255), id_exp bigint, primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), etat varchar(255), id_exp bigint, primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), primary key (id_livre)) engine=InnoDB;
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), num_livre bigint, primary key (id_livre)) engine=InnoDB;
alter table livre add constraint FK1bla74o1wimuo6tjnlablneu0 foreign key (num_livre) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), num_livre bigint, primary key (id_livre)) engine=InnoDB;
alter table livre add constraint FK1bla74o1wimuo6tjnlablneu0 foreign key (num_livre) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), num_livre bigint, primary key (id_livre)) engine=InnoDB;
alter table livre add constraint FK1bla74o1wimuo6tjnlablneu0 foreign key (num_livre) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), num_livre bigint, primary key (id_livre)) engine=InnoDB;
alter table livre add constraint FK1bla74o1wimuo6tjnlablneu0 foreign key (num_livre) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), id_domaine bigint, primary key (id_livre)) engine=InnoDB;
alter table livre add constraint FKe67xxmcmyhh7soj7dsk08vwx9 foreign key (id_domaine) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), id_domaine bigint, primary key (id_livre)) engine=InnoDB;
alter table livre add constraint FKe67xxmcmyhh7soj7dsk08vwx9 foreign key (id_domaine) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), id_domaine bigint, primary key (id_livre)) engine=InnoDB;
alter table livre add constraint FKe67xxmcmyhh7soj7dsk08vwx9 foreign key (id_domaine) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), id_domaine bigint, primary key (id_livre)) engine=InnoDB;
alter table livre add constraint FKe67xxmcmyhh7soj7dsk08vwx9 foreign key (id_domaine) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), id_domaine bigint, primary key (id_livre)) engine=InnoDB;
alter table livre add constraint FKe67xxmcmyhh7soj7dsk08vwx9 foreign key (id_domaine) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), id_domaine bigint, primary key (id_livre)) engine=InnoDB;
alter table livre add constraint FKe67xxmcmyhh7soj7dsk08vwx9 foreign key (id_domaine) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), id_domaine bigint, primary key (id_livre)) engine=InnoDB;
alter table livre add constraint FKe67xxmcmyhh7soj7dsk08vwx9 foreign key (id_domaine) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table livre (type_livre varchar(31) not null, id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), titre varchar(255), disponibilite bit, etat varchar(255), id_domaine bigint, primary key (id_livre)) engine=InnoDB;
alter table livre add constraint FKe67xxmcmyhh7soj7dsk08vwx9 foreign key (id_domaine) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table exemplaire (id_exemp bigint not null auto_increment, etat varchar(255), is_disponibilite bit, label varchar(255), id_exemplaire bigint, primary key (id_exemp)) engine=InnoDB;
create table livre (id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), nb_exemp_dispo integer, titre varchar(255), id_domaine bigint, primary key (id_livre)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, id_personne bigint not null auto_increment, adresse varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), telephone varchar(255), password varchar(255), username varchar(255), primary key (id_personne)) engine=InnoDB;
alter table exemplaire add constraint FK9xmqwlt30gx6wd9nwy3294npg foreign key (id_exemplaire) references livre (id_livre);
alter table livre add constraint FKe67xxmcmyhh7soj7dsk08vwx9 foreign key (id_domaine) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table exemplaire (id_exemp bigint not null auto_increment, etat varchar(255), is_disponibilite bit, label varchar(255), id_exemplaire bigint, primary key (id_exemp)) engine=InnoDB;
create table livre (id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), nb_exemp_dispo integer, titre varchar(255), id_domaine bigint, primary key (id_livre)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, id_personne bigint not null auto_increment, adresse varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), telephone varchar(255), password varchar(255), username varchar(255), primary key (id_personne)) engine=InnoDB;
alter table exemplaire add constraint FK9xmqwlt30gx6wd9nwy3294npg foreign key (id_exemplaire) references livre (id_livre);
alter table livre add constraint FKe67xxmcmyhh7soj7dsk08vwx9 foreign key (id_domaine) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table exemplaire (id_exemp bigint not null auto_increment, etat varchar(255), is_disponibilite bit, label varchar(255), id_exemplaire bigint, primary key (id_exemp)) engine=InnoDB;
create table livre (id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), nb_exemp integer, titre varchar(255), id_domaine bigint, primary key (id_livre)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, id_personne bigint not null auto_increment, adresse varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), telephone varchar(255), password varchar(255), username varchar(255), primary key (id_personne)) engine=InnoDB;
alter table exemplaire add constraint FK9xmqwlt30gx6wd9nwy3294npg foreign key (id_exemplaire) references livre (id_livre);
alter table livre add constraint FKe67xxmcmyhh7soj7dsk08vwx9 foreign key (id_domaine) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table exemplaire (id_exemp bigint not null auto_increment, etat varchar(255), is_disponibilite bit, label varchar(255), id_livre bigint, primary key (id_exemp)) engine=InnoDB;
create table livre (id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), nb_exemp integer, titre varchar(255), id_domaine bigint, primary key (id_livre)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, id_personne bigint not null auto_increment, adresse varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), telephone varchar(255), password varchar(255), username varchar(255), primary key (id_personne)) engine=InnoDB;
alter table exemplaire add constraint FKjrlylp63ofe9qwf6k2t0m09xh foreign key (id_livre) references livre (id_livre);
alter table livre add constraint FKe67xxmcmyhh7soj7dsk08vwx9 foreign key (id_domaine) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table exemplaire (id_exemp bigint not null auto_increment, etat varchar(255), is_disponibilite bit, label varchar(255), id_livre bigint, primary key (id_exemp)) engine=InnoDB;
create table livre (id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), nb_exemp integer, titre varchar(255), id_domaine bigint, primary key (id_livre)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, id_personne bigint not null auto_increment, adresse varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), telephone varchar(255), password varchar(255), username varchar(255), primary key (id_personne)) engine=InnoDB;
alter table exemplaire add constraint FKjrlylp63ofe9qwf6k2t0m09xh foreign key (id_livre) references livre (id_livre);
alter table livre add constraint FKe67xxmcmyhh7soj7dsk08vwx9 foreign key (id_domaine) references domaine (id);
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table exemplaire (id_exemp bigint not null auto_increment, etat varchar(255), is_disponibilite bit, label varchar(255), id_livre bigint, primary key (id_exemp)) engine=InnoDB;
create table livre (id_livre bigint not null auto_increment, auteur varchar(255), editeur varchar(255), nb_exemp integer, titre varchar(255), id_domaine bigint, primary key (id_livre)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, id_personne bigint not null auto_increment, adresse varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), telephone varchar(255), password varchar(255), username varchar(255), primary key (id_personne)) engine=InnoDB;
alter table exemplaire add constraint FKjrlylp63ofe9qwf6k2t0m09xh foreign key (id_livre) references livre (id_livre);
alter table livre add constraint FKe67xxmcmyhh7soj7dsk08vwx9 foreign key (id_domaine) references domaine (id);
