drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
drop table if exists livre;
alter table livre drop foreign key FK1bla74o1wimuo6tjnlablneu0;
drop table if exists domaine;
drop table if exists livre;
alter table livre drop foreign key FK1bla74o1wimuo6tjnlablneu0;
drop table if exists domaine;
drop table if exists livre;
alter table livre drop foreign key FK1bla74o1wimuo6tjnlablneu0;
drop table if exists domaine;
drop table if exists livre;
alter table livre drop foreign key FK1bla74o1wimuo6tjnlablneu0;
drop table if exists domaine;
drop table if exists livre;
alter table livre drop foreign key FKe67xxmcmyhh7soj7dsk08vwx9;
drop table if exists domaine;
drop table if exists livre;
alter table livre drop foreign key FKe67xxmcmyhh7soj7dsk08vwx9;
drop table if exists domaine;
drop table if exists livre;
alter table livre drop foreign key FKe67xxmcmyhh7soj7dsk08vwx9;
drop table if exists domaine;
drop table if exists livre;
alter table livre drop foreign key FKe67xxmcmyhh7soj7dsk08vwx9;
drop table if exists domaine;
drop table if exists livre;
alter table livre drop foreign key FKe67xxmcmyhh7soj7dsk08vwx9;
drop table if exists domaine;
drop table if exists livre;
alter table livre drop foreign key FKe67xxmcmyhh7soj7dsk08vwx9;
drop table if exists domaine;
drop table if exists livre;
alter table livre drop foreign key FKe67xxmcmyhh7soj7dsk08vwx9;
drop table if exists domaine;
drop table if exists livre;
alter table livre drop foreign key FKe67xxmcmyhh7soj7dsk08vwx9;
drop table if exists domaine;
drop table if exists livre;
alter table exemplaire drop foreign key FK9xmqwlt30gx6wd9nwy3294npg;
alter table livre drop foreign key FKe67xxmcmyhh7soj7dsk08vwx9;
drop table if exists domaine;
drop table if exists exemplaire;
drop table if exists livre;
drop table if exists personne;
alter table exemplaire drop foreign key FK9xmqwlt30gx6wd9nwy3294npg;
alter table livre drop foreign key FKe67xxmcmyhh7soj7dsk08vwx9;
drop table if exists domaine;
drop table if exists exemplaire;
drop table if exists livre;
drop table if exists personne;
alter table exemplaire drop foreign key FK9xmqwlt30gx6wd9nwy3294npg;
alter table livre drop foreign key FKe67xxmcmyhh7soj7dsk08vwx9;
drop table if exists domaine;
drop table if exists exemplaire;
drop table if exists livre;
drop table if exists personne;
alter table exemplaire drop foreign key FKjrlylp63ofe9qwf6k2t0m09xh;
alter table livre drop foreign key FKe67xxmcmyhh7soj7dsk08vwx9;
drop table if exists domaine;
drop table if exists exemplaire;
drop table if exists livre;
drop table if exists personne;
alter table exemplaire drop foreign key FKjrlylp63ofe9qwf6k2t0m09xh;
alter table livre drop foreign key FKe67xxmcmyhh7soj7dsk08vwx9;
drop table if exists domaine;
drop table if exists exemplaire;
drop table if exists livre;
drop table if exists personne;
alter table exemplaire drop foreign key FKjrlylp63ofe9qwf6k2t0m09xh;
alter table livre drop foreign key FKe67xxmcmyhh7soj7dsk08vwx9;
drop table if exists domaine;
drop table if exists exemplaire;
drop table if exists livre;
drop table if exists personne;
